export const projectsData = [
  {
    title: "Sigma Agency",
    link: "https://sigmaagencyjo.com",
    img: "/projects/sigma.png",
    description: "A digital agency website focused on IT services, specializing in web development, app solutions, and digital marketing for business growth.",
  },
  {
    title: "Translare",
    link: "https://translare.netlify.app/",
    img: "/projects/translare.png",
    description: "A translation and localization platform specializing in multilingual communication and helping businesses reach global markets.",
  },
  {
    title: "Naqaa",
    link: "https://naqaa.netlify.app",
    img: "/projects/naqaa.png",
    description: "A non-profit organization website focused on humanitarian work, specializing in clean water solutions and sustainable well drilling projects.",
  },
  {
    title: "Al-Sayarie",
    link: "https://al-sayarie.netlify.app",
    img: "/projects/al-sayarie.png",
    description: "A financial services website for a currency exchange company, specializing in money exchange and financial transactions.",
  },
  {
    title: "Abqari Store",
    link: "https://abqari-store.netlify.app",
    img: "/projects/abqari-store.png",
    description: "An e-commerce platform specializing in online retail and delivering a smooth shopping experience for various consumer products.",
  },
  {
    title: "Jemexshop",
    link: "https://jemexshop.netlify.app/seller-pages/welcome-page",
    img: "/projects/jemexshop.png",
    description: "A multi-vendor e-commerce platform specializing in seller dashboards, product management, and marketplace solutions.",
  },
  {
    title: "Petra MS",
    link: "https://petra-ms.netlify.app",
    img: "/projects/petra-ms.png",
    description: "A marketing solutions platform specializing in digital marketing, social media management, and SEO/SEM strategies.",
  },
  {
    title: "BlackIn",
    link: "https://blackinn.netlify.app",
    img: "/projects/blackin.png",
    description: "A digital marketing and tech solutions website specializing in creative branding, high-impact campaigns, and business software solutions.",
  },
  {
    title: "Backaldrin",
    link: "https://backaldrin.netlify.app/",
    img: "/projects/backaldrin.png",
    description: "A corporate website in the food manufacturing industry, specializing in bakery ingredients and innovative baking solutions.",
  },
  {
    title: "Qawasmi Store",
    link: "https://qawasmi.netlify.app/",
    img: "/projects/qawasmi.png",
    description: "An e-commerce store specializing in online retail with a user-friendly shopping interface and product browsing experience.",
  },
  {
    title: "Turbo",
    link: "https://turboo.netlify.app/",
    img: "/projects/turbo.png",
    description: "An industrial engineering team platform specializing in academic and practical engineering projects and development.",
  },
  {
    title: "Qawasmi Dashboard",
    link: "https://qawasmi-dashboard.netlify.app/pages/statistics",
    img: "/projects/qawasmi-dashboard.png",
    description: "An admin dashboard specializing in e-commerce management, analytics tracking, and business operations control.",
  },
  {
    title: "Blackin Dashboard",
    link: "https://blackin-dashboard.netlify.app/pages/home",
    img: "/projects/blackin-dashboard.png",
    description: "A management dashboard specializing in controlling company content, users, and performance analytics.",
  },
  {
    title: "Petra Prodduction",
    link: "https://petra-production.netlify.app/",
    img: "/projects/petra-production.png",
    description: "A media production website specializing in photography, creative shoots, and professional visual content services.",
  },
  {
    title: "Goal Makers",
    link: "https://goal-makers.netlify.app",
    img: "/projects/goal-makers.jpg",
    description: "A software and web solutions platform specializing in website development, e-commerce systems, and digital marketing services.",
  },
  {
    title: "Al Quran",
    link: "https://qor3an.netlify.app/",
    img: "/projects/qouran.png",
    description: "An architecture and interior design platform specializing in home design, visual identity, and creative architectural solutions.",
  },
  {
    title: "Arslan Sky",
    link: "https://arslan-sky.netlify.app/admin/home",
    img: "/projects/arslan-sky.png",
    description: "A financial admin dashboard specializing in data management, reporting, and business performance tracking.",
  },
  {
    title: "Odeh Desgin",
    link: "https://odeh.netlify.app",
    img: "/projects/odeh.jpg",
    description: "An architecture and design portfolio specializing in creative building concepts and professional architectural solutions.",
  },
  {
    title: "Nieroukh",
    link: "https://nieroukh.netlify.app",
    img: "/projects/nieroukh.jpg",
    description: "An e-commerce platform specializing in online product sales with a simple and accessible shopping experience.",
  },
  {
    title: "Medical Center",
    link: "https://medical-center-ya.netlify.app/",
    img: "/projects/medical-center.jpg",
    description: "A healthcare platform specializing in home medical services, patient care, and professional healthcare support.",
  },
];